include:
  - ../Server/docker-compose.yml

services:
  nginx:
    image: nginx:1.30.0
    container_name: nginx
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    volumes:
      - ./certs/:/etc/nginx/certs/:ro
      - ./templates/:/etc/nginx/templates/:ro
      - /dev/null:/etc/nginx/conf.d/default.conf
    environment:
      - PORT_EMPLOYEE=${ASPNETCORE_PORT}
      - HOST_EMPLOYEE=employee-api
      - PORT_CUSTOMER=${ASPNETCORE_PORT}
      - HOST_CUSTOMER=customer-api
      - PORT_AUTH=${KEYCLOAK_HTTP_PORT}
      - HOST_AUTH=keycloak

      - NGINX_DOMAIN=${NGINX_DOMAIN}
    depends_on:
      keycloak:
        condition: service_healthy
      employee-api:
        condition: service_healthy
      customer-api:
        condition: service_healthy
    networks:
      - nginx-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 5s
      timeout: 10s
      retries: 5
    restart: unless-stopped

networks:
  nginx-network:
    driver: bridge