table payment{
    id int [pk]
    amount decimal
    payment_date date
    method_id int
    status_id int
}

table payment_status{
    id int [pk]
    name string
}

table payment_method{
    id int [pk]
    name string
}

ref {payment.method_id > payment_method.id}
ref {payment.status_id > payment_status.id}