services:

  keycloak:
    image: keycloak/keycloak:26.6.1
    container_name: keycloak
    command: "start-dev"
    ports:
      - ${KEYCLOAK_HTTP_PORT}:${KEYCLOAK_HTTP_PORT}
    networks:
      - keycloak-network
      - nginx-network
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${ADMIN_NAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true

      KC_HTTP_ENABLED: true
      KC_HTTP_PORT: ${KEYCLOAK_HTTP_PORT}
      KC_HOSTNAME: ${KEYCLOAK_HOST}
      KC_PROXY_HEADERS: xforwarded

      KC_DB_DEBUG_JPQL: true
      KC_DB: postgres
      KC_DB_USERNAME: ${KC_POSTGRES_USER}
      KC_DB_PASSWORD: ${KC_POSTGRES_PASSWORD}
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/${KC_POSTGRES_DB}
    depends_on:
      keycloak-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "exec 3<> /dev/tcp/localhost/9000; echo -e 'GET /health/ready HTTP/1.1\\r\\nhost: localhost\\r\\nConnection: close\\r\\n\\r\\n' >&3; if [ $? -eq 0 ]; then echo 'Healthcheck Successful'; exit 0; else echo 'Healthcheck Failed'; exit 1; fi;"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always

  keycloak-db:
    image: postgres:18.3
    container_name: keycloak-db
    ports:
      - ${KC_POSTGRES_PORT}:5432
    networks:
      - keycloak-network
    environment:
      POSTGRES_DB: ${KC_POSTGRES_DB}
      POSTGRES_USER: ${KC_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KC_POSTGRES_PASSWORD}
    volumes:
      - kc_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${KC_POSTGRES_USER} -d ${KC_POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  terraform:
    image: hashicorp/terraform:1.15.1
    container_name: terraform
    volumes:
      - ./Terraform:/Terraform
      - ./terraform-config:/root/.terraformrc
      - tf-plugin-caches:/Terraform/.terraform.d/plugin-cache
    networks:
      - keycloak-network
    working_dir: /Terraform
    entrypoint: ["/bin/sh", "-c", "terraform init && terraform plan && terraform apply -auto-approve && sleep infinity"]
    environment:
      - TF_IN_AUTOMATION=true
      - TF_PLUGIN_CACHE_DIR=/Terraform/.terraform.d/plugin-cache

      - TF_VAR_employee_realm=${KEYCLOAK_EMPLOYEE_REALM}
      - TF_VAR_employee_client_id=${KEYCLOAK_EMPLOYEE_RESOURCE}
      - TF_VAR_employee_client_secret=${KEYCLOAK_EMPLOYEE_SECRET}

      - TF_VAR_customer_realm=${KEYCLOAK_CUSTOMER_REALM}
      - TF_VAR_customer_client_id=${KEYCLOAK_CUSTOMER_RESOURCE}
      - TF_VAR_customer_client_secret=${KEYCLOAK_CUSTOMER_SECRET}

      - TF_VAR_admin_username=${ADMIN_NAME}
      - TF_VAR_admin_password=${ADMIN_PASSWORD}
      - TF_VAR_kc_url=http://keycloak:${KEYCLOAK_HTTP_PORT}
    depends_on:
      keycloak:
        condition: service_healthy
    restart: always

volumes:
  tf-plugin-caches:
  kc_data:

networks:
  keycloak-network:
    driver: bridge
  nginx-network:
    driver: bridge