table room{
    id int [pk]
    hotel_id int
    room_type_id int
    room_number int
    floor int
    room_status_id int
}

table room_status{
    id int [pk]
    name string
}

table room_type{
    id int [pk]
    name string
    description string
    base_price decimal
    max_count_guest int
}

table room_tag{
    id int [pk]
    name string
    description string
}

table room_room_tag{
    room_id int [pk]
    room_tag_id int [pk]
}

table room_image{
    room_id int [pk]
    image_key string [pk]
}

ref {room_status.id < room.room_status_id}
ref {room_type.id < room.room_type_id}
ref {room.id < room_room_tag.room_id}
ref {room_tag.id < room_room_tag.room_tag_id}
ref {room.id < room_image.room_id}