table hotel {
    id int [pk]
    location point
    email string
    phone string
}

table hotel_tag{
    id int [pk]
    name string
    description string
}

table hotel_hotel_tag{
    hotel_id int [pk]
    hotel_tag_id int [pk]
}

table hotel_image{
    hotel_id int [pk]
    image_key string [pk]
}

ref {hotel.id < hotel_hotel_tag.hotel_id}
ref {hotel_tag.id < hotel_hotel_tag.hotel_tag_id}
ref {hotel.id < hotel_image.hotel_id}